testExcel/api_test/urls.py
from django.contrib import admin
from django.urls import include, path
from api_test.views import Catered, OperateurRUD,CateredDdva, OperateurView, TacheRUD, TacheView, Test_view,Reconcile,Cinetpay 
from api_test import views
from rest_framework.authtoken.views import obtain_auth_token 
from rest_framework.routers import DefaultRouter


app_name='api_test'
urlpatterns = [
    path('reconciliation/', Reconcile.as_view(), name='reconciliation'),
    path('reconciliation/verification/', Reconcile.as_view(), name='reconcile'),
    path('catered/', Catered.as_view(), name='catered'),
    path('cinetpay/', Cinetpay.as_view(), name='cinetpay'),
    # path('auth/', include('rest_framework_social_oauth2.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('authentication/', include('users.urls')),
    path('operateurs/', OperateurView.as_view(), name='olc'),
    path('operateurs/<int:pk>/', OperateurRUD.as_view(), name='orud'),
    path('taches/', TacheView.as_view(), name='tlc'),
    path('taches/<int:pk>/', TacheRUD.as_view(), name='trud'),
    path('catered_ddva/', CateredDdva.as_view(), name='catered_ddva'),
    
]

testExcel/reconcile/urls.py
from django.urls import path

from . import views


app_name='reconcile'
urlpatterns = [
    path('', views.index, name='index'),
    path('excel-to-json/', views.excel_to_json, name='excel_to_json'),
    path('reconcile/', views.reconcile, name='reconcile'),
    path('update_transaction/', views.update_transaction, name='update_transaction'),
]

testExcel/testExcel/urls.py
from django.contrib import admin
from django.urls import include, path
from api_test.views import OperateurRUD,ReconcileUpdate,UpdateProfile,TrxRightCorrespodentb,TrxRightCorrespodentRUDView,TrxDifferenceRUDView,TrxDifferenceView, OperateurView,ProfileView,ProfileRUD, TacheRUD, TacheView,TokenView, Test_view,Reconcile,Cinetpay
from api_test import views
from rest_framework.authtoken.views import obtain_auth_token 
from rest_framework.routers import DefaultRouter


urlpatterns = [
    path('reconcile/', include('reconcile.urls')),
    path('api_test/', include('api_test.urls')),
    path('admin/', admin.site.urls),
    path('get_user/',TokenView.as_view(),name="token"),
    path('', Test_view.as_view(), name='test'),
    path('reconciliation/', Reconcile.as_view(), name='reconcile'),
    path('update_reconciliation/<int:pk>/', ReconcileUpdate.as_view(), name='reconcile'),
    path('reconciliation/verification/', Reconcile.as_view(), name='reconcile'),
    path('cinetpay/', Cinetpay.as_view(), name='cinetpay'),
    # path('auth/', include('rest_framework_social_oauth2.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('authentication/', include('users.urls')),
    path('operateurs/', OperateurView.as_view(), name='olc'),
    path('operateurs/<int:pk>/', OperateurRUD.as_view(), name='orud'),
    path('profiles/', ProfileView.as_view(), name='plc'),
    path('profiles/<int:pk>/', ProfileRUD.as_view(), name='prud'),
    path('update_profile/', UpdateProfile.as_view(), name='updp'),
    path('taches/', TacheView.as_view(), name='tlc'),
    path('taches/<int:pk>/', TacheRUD.as_view(), name='trud'),
    path('<int:tache_id>/trxdifferences/', TrxDifferenceView.as_view(), name='trxdifferences'),
    path('<int:tache_id>/trxdifferences/<int:pk>/', TrxDifferenceRUDView.as_view(), name='trxdifference'),
    path('<int:tache_id>/trxrightcorrespodent/', TrxRightCorrespodentb.as_view(), name='trxrightcorrespodent'),
    path('<int:tache_id>/trxrightcorrespodent/<int:pk>/', TrxRightCorrespodentRUDView.as_view(), name='rudtrxrightcorrespodent'),
    # path('export/<int:pk>/', ExportFile.as_view(), name='trud'),
]

testExcel/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('register/', views.register),
    path('token/', views.token),
    path('token/refresh/', views.refresh_token),
    path('token/revoke/', views.revoke_token),
]

testExcel/reconcile/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from . import models
from .models import TrxOperateur, TrxCinetpay,TrxFailedCinetpay,TrxDifference,TrxCorrespondent,TrxDifference,TrxCorrespondent,TrxRightCorrespodent,TrxSuccessCinetpay
from django.core import serializers
import json
import time
from queue import Empty, Queue
from threading import Thread
import concurrent.futures
from datetime import datetime
from django.db.models import Sum,Avg


# # Operator insertion-------------------------------------------------------------------------------------------------------------------------
# def insert_data(x):
#     b =TrxOperateur(datepaiment=x['Datepaiment'], idpaiment=x['idpaiment'],status=x['Statut'],telephone=x['telephone'],montant=x['Montant'])
#     b.save()
#     print('sauvé')
#----------------------------------------------------------------------------------------------------------------------------------------------

# Orange Operator insertion precisely----------------------------------------------------------------------------------------------------------
# def insert_data(x):
#     b =TrxOperateur(datepaiment=x['date'] +" "+ x['heure'], idpaiment=x['idpaiment'],status=x['status'],telephone=x['telephone'],montant=x['montant'])
#     b.save()
#     print('sauvé')
#----------------------------------------------------------------------------------------------------------------------------------------------

# # Cinetpay-----------------------------------------------------------------------------------------------------------------------------------
def insert_data(x):
    b =TrxCinetpay(creation=x['CREATION'],datePaiement=x['DATE PAIEMENT'],marchand=x['MARCHAND'],
    NomDuService=x['NOM DU SERVICE'],IdTransaction=x['ID TRANSACTION'],
    SiteId=x['SITE_ID'],Montant=x['MONTANT'],methodePaiment=x['METHODE PAIEMENT'],
    Telephone=x['TELEPHONE'],EtatTransaction=x['ETAT TRANSACTION'],IdPaiment=x['ID PAIEMENT'])
    b.save()
    print('sauvé')
#----------------------------------------------------------------------------------------------------------------------------------------------


# Insertion of failed transactions from Cinetpay-----------------------------------------------------------------------------------------------
# def insert_data(x):
#     b =TrxFailedCinetpay(creation=x.creation,datePaiement=x.datePaiement,marchand=x.marchand,EmailMarchand=x.EmailMarchand,
#     NomDuService=x.NomDuService,IdTransaction=x.IdTransaction,
#     SiteId=x.SiteId,Montant=x.Montant,methodePaiment=x.methodePaiment,
#     Telephone=x.Telephone,EtatTransaction=x.EtatTransaction,IdPaiment=x.IdPaiment)
#     b.save()
#     print('sauvé')
#----------------------------------------------------------------------------------------------------------------------------------------------

# Insertion of trx correspondent---------------------------------------------------------------------------------------------------------------
def insert_correspondent(x):
    b =TrxCorrespondent(creation=x.creation,datePaiement=x.datePaiement,marchand=x.marchand,EmailMarchand=x.EmailMarchand,
    NomDuService=x.NomDuService,IdTransaction=x.IdTransaction,
    SiteId=x.SiteId,Montant=x.Montant,methodePaiment=x.methodePaiment,
    Telephone=x.Telephone,EtatTransaction=x.EtatTransaction,IdPaiment=x.IdPaiment)
    b.save()
    print('sauvé')
#--------------------------------------------------------------------------------------------------------------------------------------------

# Insertion correspondent of each transaction------------------------------------------------------------------------------------------------
def insert_finalCorrespondant(x,t):
    b =TrxRightCorrespodent(datePaiement =x.datepaiment,idpaiment=x.idpaiment,status =x.status,telephone=x.telephone,montant = x.montant,
    creationCorrespondent =t.creation,AmountCorrespodent=t.Montant,methodePaimentCorrespondant=t.methodePaiment,
    TelephoneCorrespondant=t.Telephone,StautTransactionCorrespondent=t.EtatTransaction,IdTransactionCorrespondent = t.IdTransaction)
    b.save()
    print('sauvé')
#---------------------------------------------------------------------------------------------------------------------------------------------

# Insertion transaction from operator and not from Cinetpay (difference)----------------------------------------------------------------------
# def insert_data(x):
#     b =TrxDifference(datepaiment=x.datepaiment, idpaiment=x.idpaiment,status=x.status,telephone=x.telephone,montant=x.montant)
#     b.save()
#     print('sauvé')
#---------------------------------------------------------------------------------------------------------------------------------------------


# # competitive approach-----------------------------------------------------------------------------------------------------------------------
# def concurent_manager():
#     NUM_WORKERS = 20
#     start_time = time.time()
#     with concurrent.futures.ThreadPoolExecutor(max_workers = NUM_WORKERS) as executor :
#         futures = {executor.submit(insert_data(trx), trx) for trx in TRANSACTION_LIST}
#         concurrent.futures.wait(futures)
#     end_time = time.time()
#     print("Time for inserting : %ssecs" % (end_time-start_time) )
    
# TRANSACTION_LIST = []
# def reconcile(request):
    
#     if request.method == 'POST' :
#         transaction = request.POST['valeur']
#         trx = json.loads(transaction)
#         for x in trx :
#             TRANSACTION_LIST.append(x)

#     concurent_manager()
#     return render(request, 'reconcile/excel_to_json.html')

# ---------------------------------------------------------------------------------------------------------------------------------------------




# Approach by task ----------------------------------------------------------------------------------------------------------------------------
def task_manager():

    NUM_WORKERS = 2
    task_queue = Queue()
    def worker ():
        while True :
            data = task_queue.get()
            insert_data(data)

            task_queue.task_done()
    start_time = time.time()
    threads = [Thread(target=worker) for _ in range(NUM_WORKERS)]

    [task_queue.put(item) for item in TRANSACTION_LIST]

    [thread.start() for thread in threads]

    task_queue.join()

    end_time = time.time()
    print("Time for inserting : %ssecs" % (end_time-start_time) )
#---------------------------------------------------------------------------------------------------------------------------------------------


#transaction from operator and not from Cinetpay----------------------------------------------------------------------------------------------
# def match_table():
#     difference = TrxOperateur.objects.exclude(idpaiment__in=TrxCinetpay.objects.values_list('IdPaiment', flat=True))
#     print(len(difference))
#     return difference
#     # for x in ecart :
#     #     print(x)
#     # detect_correspondent(ecart)
#----------------------------------------------------------------------------------------------------------------------------------------------

def compare_date(first,second):
    # zero_obj = datetime.strptime('first', '%Y-%m-%d %H:%M:%S')
    # print(type(first))
    # print(type(second))
    # diff = first - second
    # print(diff)
    if (first <= second):
        return True
    else :
        return False



# #ONECI MTNCI---------------------------------------------------------------------------------------------------------------------------------
# def Cinetpay_transaction_success(first,last):
#     success_trx = []  
#     all_trx = TrxCinetpay.objects.all()
#     # create a function for this and use task_manager
#     for trx in all_trx :
#         if trx.datePaiement != "null" and trx.IdPaiment !="null" and trx.methodePaiment=="MOMO" and trx.marchand =="ONECI - RNPP" and trx.NomDuService=="ONECI":            
#             trx_obj = datetime.strptime(trx.datePaiement, '%Y-%m-%d %H:%M:%S')
#             if trx_obj <= last and trx_obj >= first :
#                 success_trx.append(trx)
#     print(len(success_trx))
#     return success_trx
# ---------------------------------------------------------------------------------------------------------------------------------------------


# #ONECI MTNCI---------------------------------------------------------------------------------------------------------------------------------
# def Cinetpay_transaction_failed(first,last):
#     failed_trx = []  
#     all_trx = TrxCinetpay.objects.all()
#     # create a function for this and use task_manager
#     for trx in all_trx :
#         if trx.EtatTransaction != "Successfully Processed Transaction" and trx.methodePaiment=="MOMO" and trx.marchand =="ONECI - RNPP" and trx.NomDuService=="ONECI":            
#             trx_obj = datetime.strptime(trx.datePaiement, '%Y-%m-%d %H:%M:%S')
#             if trx_obj <= last and trx_obj >= first :
#                 failed_trx.append(trx)
#     print(len(failed_trx))
#     return failed_trx
# --------------------------------------------------------------------------------------------------------------------------------------------



#DDVA MTNCI------------------------------------------------------------------------------------------------------------------------------------
# def Cinetpay_transaction_success(first,last):
#     success_trx = []  
#     all_trx = TrxCinetpay.objects.all()
#     # create a function for this and use task_manager
#     for trx in all_trx :
#             if trx.EtatTransaction=="SUCCES" and trx.methodePaiment=="DDVAMTNCI" and trx.marchand =="DDVA" :            
#                 trx_obj = datetime.strptime(trx.datePaiement, '%Y-%m-%d %H:%M:%S')
#                 if trx_obj <= last and trx_obj >= first :
#                     success_trx.append(trx)
#     print(len(success_trx))
#     return success_trx

testExcel/reconcile/templates/reconcile/display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DiSPLAY DATA</title>

    <style>
        #transaction {
          font-family: Arial, Helvetica, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        #transaction td, #transaction th {
          border: 1px solid #ddd;
          padding: 8px;
        }
        
        #transaction tr:nth-child(even){background-color: #f2f2f2;}
        
        #transaction tr:hover {background-color: #ddd;}
        
        #transaction th {
          padding-top: 12px;
          padding-bottom: 12px;
          text-align: left;
          background-color: #4CAF50;
          color: white;
        }
    </style>
</head>
<body>
    <p>Nombre total des transactions (operateur) : <strong>{{ countOperator }}</strong> </p>
    <p>Nombre total des transactions (Cinetpay) : <strong>{{ countCinetpay }}</strong> </p>
    <p>Nombre total de transactions à réconcilier : <strong>{{ diffCount }}</strong> </p>
    <p>Montant total des transactions (operateur) : <strong>{{ total.montant__sum }}  FCFA</strong> </p>
    <p>Montant total des transactions (Cinetpay) : <strong>{{montantCinetpay.Montant__sum}} FCFA</strong> </p>
    <p>Difference Montant : <strong>{{diffMontant}}</strong> </p>
    
    <table id="transaction">
 
        <h1 style="margin-left: 90px;">LES CORRESPONDANTS DES TRANSACTIONS ECHEC CHEZ CINETPAY</h1>
       <tr>
           <th>DATE PAIMENT</th>
           <th>ID PAIMENT</th>
           <th>TELEPHONE</th>
           <th>MONTANT</th>
           <th>STATUT</th>
           <th>DATE CREATION CINETPAY</th>
           <th>ID TRANSACTION CINETPAY</th>
           <th>TELEPHONE CINETPAY</th>
           <th>MONTANT CINETPAY</th>
           <th>STATUT CINETPAY</th>
       </tr>
       <tbody>
            {% for data in correspondent %}
            <tr>
                 <td>{{ data.datePaiement}}</td> 
                 <td>{{ data.idpaiment }}</td> 
                 <td>{{ data.telephone }}</td> 
                 <td>{{ data.montant }}</td> 
                 <td>{{ data.status }}</td> 
                 <td>{{ data.creationCorrespondent }}</td> 
                 <td>{{ data.IdTransactionCorrespondent }}</td> 
                 <td>{{ data.TelephoneCorrespondant }}</td> 
                 <td>{{ data.AmountCorrespodent }}</td> 
                 <td>{{ data.StautTransactionCorrespondent }}</td> 
            </tr>
            {% endfor %}
       </tbody>
       
    </table>

    <table id="transaction">
 
        <h1 style="margin-left: 90px;">LES TRANSACTIONS DE L'OPERATEUR SANS CORRESPONDANTS</h1>
       <tr>
           <th>DATE PAIMENT</th>
           <th>ID PAIMENT</th>
           <th>TELEPHONE</th>
           <th>MONTANT</th>
           <th>STATUT</th>
       </tr>
       <tbody>
            {% for data in difference %}
            <tr>
                 <td>{{ data.datepaiment }}</td> 
                 <td>{{ data.idpaiment }}</td> 
                 <td>{{ data.telephone }}</td> 
                 <td>{{ data.montant }}</td> 
                 <td>{{ data.status }}</td> 
            </tr>
            {% endfor %}
       </tbody>      
    </table>  
    
    <form action="{% url 'reconcile:update_transaction' %}" method="POST">
        {% csrf_token %}
        <div>
            <button type="submit" style="margin-left: 1000px;">Mettre à jour</button>
        </div>
    </form>
</body>
</html>

testExcel/reconcile/templates/reconcile/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error file</title>
    <style>
        #transaction {
          font-family: Arial, Helvetica, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        #transaction td, #transaction th {
          border: 1px solid #ddd;
          padding: 8px;
        }
        
        #transaction tr:nth-child(even){background-color: #f2f2f2;}
        
        #transaction tr:hover {background-color: #ddd;}
        
        #transaction th {
          padding-top: 12px;
          padding-bottom: 12px;
          text-align: left;
          background-color: #4CAF50;
          color: white;
        }
    </style>
</head>
<body>
    <table id="transaction">
        <tr> 
            <th>Ligne </th>    
            <th>DATE </th>
            <th>HEURE</th>
            <th>ID PAIEMENT</th>
            <th>STATUT</th>
            <th>MONTANT</th>
            <th>TELEPHONE</th>
        </tr>
        <tbody>
        {% for data in file %}
             {% if forloop.counter0  in etat %}
            <tr style="color: red;">
                <th>{{forloop.counter0}} </th>
                <td>{{ data.date }}</td> 
                <td>{{ data.heure }}</td> 
                <td>{{ data.idpaiment }}</td> 
                <td>{{ data.status }}</td> 
                <td>{{ data.montant }}</td> 
                <td>{{ data.telephone }}</td> 
            </tr>
     
             {% endif %}

        {% endfor %}
         </tbody>      
    </table>  
   
     
</body>
</html>

testExcel/reconcile/templates/reconcile/excel_to_json.html
{% load static %}
    <!DOCTYPE html>
    <html lang="en">
    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
            crossorigin="anonymous">
        <title>Convert excel to JSON Object</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.16.2/xlsx.full.min.js"></script>
        <script type="text/javascript" src="{% static 'jquery.js' %}" ></script>
    </head>
    
    <body>  
        <form action="{% url 'api_test:reconciliation' %}" method="POST" >
            {% csrf_token %}
        <div class="conatiner mt-5">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-3">
                    <input class="form-control" type="file" id="input" accept=".xls,.xlsx" name="excel" >
                </div>
                <div class="col-md-2">
                    <input type="button"class="btn btn-primary" id="button" value="Convert">
                </div>
                <!-- <div>
                    <input type="datetime-local" placeholder="debut" id ="debut" name="debut">
                    <input type="datetime-local" placeholder="fin" id ="fin" name="fin">
                </div> -->
                <div>
                    <!--Blue select-->
                    <select name="operateur"  class="mdb-select md-form colorful-select dropdown-primary" style="margin-left: 950px;">
                        <option value="OMCI" >ORANGE CI</option>
                        <option value="DDVAOMCI" >DDVA ORANGE CI</option>
                        <option value="OMONECI" >ONECI ORANGE CI</option>
                        <option value="MTNCI" >MTN CI</option>
                        <option value="DDVAMTNCI">DDVA MTN CI</option>
                        <option value="ONECIMTN" >ONECI MTN CI</option>
                        <option value="MOOVCI" >MOOV CI</option>
                        <option value="DDVAMOOV" >DDVA MOOV CI</option>
                        <option value="ONECIMOOV" >ONECI MOOV CI</option>
                        <option value="DDVAVISA" >DDVA VISA</option>
                        <option value="OMSN">ORANGE SENEGAL</option>
                        <option value="FREESN" >Free SENEGAL</option>
                        <option value="MTNCM" >MTN CM</option>
                        <option value="OMCM" >ORANGE CM</option>
                        <option value="OMBF" >ORANGE BK</option>
                        <option value="MOOVBK" >MOOV BK</option>
                        <option value="MOOVTG" >MOOV TG</option>
                        <option value="OMRDC" >ORANGE RDC</option>
                    </select>
                    <label class="mdb-main-label"><strong>Operateur</strong> </label>
                    <!--/Blue select-->
                </div>
    <div class="col-md-12">
        <pre id="jsondata"></pre>
        <input type="hidden" id="fichier" name="fichier">
    </div>
            </div>
        </div>
        <button type="submit">Envoyer</button>
    </form>
    </body>
    <script>
        let selectedFile;
    console.log(window.XLSX);
    document.getElementById('input').addEventListener("change", (event) => {
        selectedFile = event.target.files[0];
    })
    
    let data=[{
        "name":"jayanth",
        "data":"scd",
        "abc":"sdef"
    }]
    
    
    document.getElementById('button').addEventListener("click", () => {
        XLSX.utils.json_to_sheet(data, 'out.xlsx');
        if(selectedFile){
            let fileReader = new FileReader();
            fileReader.readAsBinaryString(selectedFile);
            fileReader.onload = (event)=>{
             let data = event.target.result;
             let workbook = XLSX.read(data,{type:"binary"});
             console.log(workbook);
    
            var tab = [];
            workbook.SheetNames.forEach(sheet => {
                  let rowObject = XLSX.utils.sheet_to_row_object_array(workbook.Sheets[sheet]);
                  console.log(rowObject);
                  console.log(rowObject[0].name);
                  document.getElementById("jsondata").innerHTML = JSON.stringify(rowObject,undefined,4)
                  tab = rowObject;
                  
             });
            $("#fichier").val(JSON.stringify(tab,undefined,4));
            }
        
        }
    });
    
    
    </script>
    
    </html>
    